[profile.dev]
opt-level = 0
debug = true
incremental = true

[workspace]
members = [
    "crates/game_core",
    "crates/game_logic",
    "crates/game_runtime",
    "crates/build_support",
]
resolver = "3"
